
FROM maven:3.9-openjdk-17-slim AS build
WORKDIR /build

COPY pom.xml .

# This ensures the structure is /build/backend/src...
COPY backend ./backend

RUN mvn clean package -pl backend -am -DskipTests

FROM openjdk:17-slim
WORKDIR /app

COPY --from=build /build/backend/target/peerlink.jar app.jar

COPY --from=build /build/backend/target/dependency/*.jar ./lib/

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
